name: 'build-createAddresses'
on: [
  workflow_dispatch
]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build
      - run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config user.name "wild.lycaon"
            git config user.email "wild.lycaon@gmail.com"
            git add .
            git commit -m "action result"
            git pull
            git push origin master
          fi
