name: 'build-createAddresses'
on: [
  workflow_dispatch
]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build
      - run: |
          git add -A .
          git config user.name "wild.lycaon"
          git config user.email "wild.lycaon@gmail.com"
          git commit -m "action result"
          git pull
          git push origin master
