name: 'createAddresses'
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run create:addr
      - run: |
          git config user.name "wild.lycaon"
          git config user.email "wild.lycaon@gmail.com"
          git add -A
          git commit -m "action result"
          git push -f origin main
